debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    kr.tripstore.kopringjpaexample: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb
